version: "3.9"
services:      
  raspberrypi_1:
    container_name: raspberrypi_1
    build: 
      context: ./raspberrypi_1
      dockerfile: Dockerfile
    ports:
      - "4000:1880"

  raspberrypi_2:
    container_name: raspberrypi_2
    build: 
      context: ./raspberrypi_2
      dockerfile: Dockerfile
    ports:
      - "4001:1880"
    
  mqttclient:
    container_name: mqttclient
    build: 
      context: ./mqttclient
      dockerfile: Dockerfile       
    ports:
      - "1880:1880"
  
  database:
    container_name: database
    image: influxdb
    ports:
      - "5000:8086"
    environment:  
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=arqiva_admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=refried-stoppage-aerobics
      - DOCKER_INFLUXDB_INIT_ORG=Arqiva
      - DOCKER_INFLUXDB_INIT_BUCKET=TransmitterPower

      
  dashboard:
    container_name: dashboard
    build: 
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  broker:
    container_name: broker
    image: rmohr/activemq:5.14.5-alpine
    ports:
      #AMQP
      - "5672:5672"
      #UI
      - "8161:8161"
      #JMS
      - "61616:61616"
      #WS
      - "61614:61614"
      #STOMP
      - "61613:61613"
      #MQTT
      - "1883:1883"