{
 "title": "ArqivaTempTransmitter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "List Of Sites",
   "type": "dashlist",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:350%;font-weight:bold;color:#C8D200;\">Temperature Transmitters</p>\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Power Levels",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"TransmitterPower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TransmitterReadings\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"powerLevel\")\r\n  |> filter(fn: (r) => r[\"site\"] == \"Black_Hill\" or r[\"site\"] == \"Blaenplwyf\" or r[\"site\"] == \"Holme Moss\" or r[\"site\"] == \"North Hessary Tor\" or r[\"site\"] == \"Rowridge\" or r[\"site\"] == \"Sandale\" or r[\"site\"] == \"Tacolneston\" or r[\"site\"] == \"Wrotham\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Site Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 19, "w": 8, "x": 7, "y": 3 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"TransmitterPower\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"TransmitterReadings\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"geohash\" or r[\"_field\"] == \"tempIn\" or r[\"_field\"] == \"sitecode\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}