version: "3.9"
services:
  sender:
    container_name: sender
    image: nodered/node-red:latest-minimal
    ports:
      - "4000:1880"
    volumes:
      - "sender-data:/opt/sender/config"

  mqttclient:
    container_name: mqttclient
    image: nodered/node-red:latest-minimal
    ports:
      - "1880:1880"
    volumes:
      - "mqttclient-data:/opt/mqttclient/config"
  
  database:
    container_name: database
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - "database-data:/opt/database/config"
  
  broker:
    container_name: broker
    image: rmohr/activemq:5.14.5-alpine
    ports:
      #AMQP
      - "5672:5672"
      #UI
      - "8161:8161"
      #JMS
      - "61616:61616"
      #WS
      - "61614:61614"
      #STOMP
      - "61613:61613"
      #MQTT
      - "1883:1883"
    volumes:
        - "broker-data:/opt/broker/conf"

volumes:
  sender-data: {}
  mqttclient-data: {}
  database-data: {}
  broker-data: {}
