version: "3.9"
services:
  raspberrypi_1:
    container_name: raspberrypi_1
    image: nodered/node-red:latest-minimal
    ports:
      - "4000:1880"
    volumes:
      - "raspberrypi_1_data:/data"

  raspberrypi_2:
    container_name: raspberrypi_2
    image: nodered/node-red:latest-minimal
    ports:
      - "4001:1880"
    volumes:
      - "raspberrypi_2_data:/data"
  
  mqttclient:
    container_name: mqttclient
    image: nodered/node-red:latest-minimal
    ports:
      - "1880:1880"
    volumes:
      - "mqttclient_data:/data"
  
  database:
    container_name: database
    image: influxdb
    ports:
      - "5000:8086"
    volumes:
      - "database_data:/data"
  
  dashboard:
    container_name: dashboard
    image: grafana/grafana
    ports:
      - "3000:3000"    
    volumes:
      - "dashboard_data:/data"

  broker:
    container_name: broker
    image: rmohr/activemq:5.14.5-alpine
    ports:
      #AMQP
      - "5672:5672"
      #UI
      - "8161:8161"
      #JMS
      - "61616:61616"
      #WS
      - "61614:61614"
      #STOMP
      - "61613:61613"
      #MQTT
      - "1883:1883"
    volumes:
        - "broker_data:/data"

volumes:
  raspberrypi_1_data: {}
  raspberrypi_2_data: {}
  mqttclient_data: {}
  database_data: {}
  dashboard_data: {}
  broker_data: {}